apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-yasc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-86-tenant/test-rhtap-86-app/devfile-sample-code-with-quarkus-yasc@sha256:03f5cfc4433842ac13f6cf56ceed0ab1df94a302da4b6cf2e1ef46ec96c75d3b
        name: my-java-quarkus
        resources: {}
status: {}
